# Generated by Django 4.1.7 on 2023-03-21 10:42

from django.db import migrations


def create_statuses(apps, schema_editor):
    Statuses = apps.get_model('crm', 'Statuses')

    first_status = Statuses(status_name='В работе')
    first_status.save()

    second_status = Statuses(status_name='Отменено')
    second_status.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_statuses)
    ]

