# Generated by Django 4.1.7 on 2023-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_creeate_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike_name', models.CharField(max_length=100)),
                ('hike_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
