# Generated by Django 4.1.7 on 2023-03-21 12:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_create_hikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=255)),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None)),
            ],
        ),
    ]
