# Generated by Django 4.1.7 on 2023-03-21 10:42

from django.db import migrations
from crm.initial_data import clients_data


def create_clients(apps, schema_editor):
    Clients = apps.get_model('crm', 'Clients')

    first_client = Clients(
        client_name = clients_data.first_client_name,
        client_email = clients_data.first_client_email,
        client_phone = clients_data.first_client_phone,
    )
    first_client.save()

    second_client = Clients(
        client_name = clients_data.second_client_name,
        client_email = clients_data.second_client_email,
        client_phone = clients_data.second_client_phone,
    )
    second_client.save()

    third_client = Clients(
        client_name = clients_data.third_client_name,
        client_email = clients_data.third_client_email,
        client_phone = clients_data.third_client_phone,
    )
    third_client.save()

    fourth_client = Clients(
        client_name = clients_data.fourth_client_name,
        client_email = clients_data.fourth_client_email,
        client_phone = clients_data.fourth_client_phone,
    )
    fourth_client.save()

    fifth_client = Clients(
        client_name = clients_data.fifth_client_name,
        client_email = clients_data.fifth_client_email,
        client_phone = clients_data.fifth_client_phone,
    )
    fifth_client.save()

    sixth_client = Clients(
        client_name = clients_data.sixth_client_name,
        client_email = clients_data.sixth_client_email,
        client_phone = clients_data.sixth_client_phone,
    )
    sixth_client.save()

    seventh_client = Clients(
        client_name = clients_data.seventh_client_name,
        client_email = clients_data.seventh_client_email,
        client_phone = clients_data.seventh_client_phone,
    )
    seventh_client.save()

    eighth_client = Clients(
        client_name = clients_data.eighth_client_name,
        client_email = clients_data.eighth_client_email,
        client_phone = clients_data.eighth_client_phone,
    )
    eighth_client.save()

    ninth_client = Clients(
        client_name = clients_data.ninth_client_name,
        client_email = clients_data.ninth_client_email,
        client_phone = clients_data.ninth_client_phone,
    )
    ninth_client.save()

    tenth_client = Clients(
        client_name = clients_data.tenth_client_name,
        client_email = clients_data.tenth_client_email,
        client_phone = clients_data.tenth_client_phone,
    )
    tenth_client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_clients'),
    ]

    operations = [
        migrations.RunPython(create_clients)
    ]

