# Generated by Django 4.1.7 on 2023-03-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_hikes_hike_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsForHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clients')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.hikes')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.statuses')),
            ],
        ),
    ]
