# Generated by Django 4.1.7 on 2023-03-21 13:16

from django.db import migrations
import random

def get_random_status(Statuses):
    return Statuses.objects.order_by('?').first()

def get_random_ordered_clients(Clients):
    return Clients.objects.order_by('?')

def get_random_client(random_ordered_clients, number_of_application):
    return random_ordered_clients[number_of_application]

def create_applications_for_hike(apps, schema_editor):
    ApplicationsForHike = apps.get_model('crm', 'ApplicationsForHike')
    Hikes = apps.get_model('crm', 'Hikes')
    Clients = apps.get_model('crm', 'Clients')
    Statuses = apps.get_model('crm', 'Statuses')

    for hike in Hikes.objects.all():
        random_ordered_clients = get_random_ordered_clients(Clients)
        number_of_applications = random.randint(1, 5)

        for number_of_application in range(number_of_applications):
            client = get_random_client(random_ordered_clients, number_of_application)

            status = get_random_status(Statuses)

            new_application = ApplicationsForHike(
                hike=hike,
                client=client,
                status=status,
            )
            new_application.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_applicationsforhike'),
    ]

    operations = [
        migrations.RunPython(create_applications_for_hike)
    ]
